services:
  db:
    image: postgres
    container_name: postgress-backend-02
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5434:5432"

  app:
    container_name: nestjs-302-backend-02
    build:
      context: ..
      dockerfile: .docker_302/Dockerfile
    ports:
      - "3003:3000"
    volumes:
      - ../app:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://myuser:mypassword@db:5432/mydatabase?schema=public"

volumes:
  db-data: