apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3003  # Port bên trong container
      nodePort: 30007   # Port ngoài Minikube (có thể đổi)
  type: NodePort
